site_name: Automatização DCMEFO
site_url: https://ottocota.github.io/cursoaid/
theme:
  name: material
  palette:
    primary: black
    accent: red

  features:
    - toc.integrate
  hide:
    - navigation
 